fix: disabling for tooltip activator added [WTEL-4631]
webitel/webitel-ui-sdk pull request #253
Opened 2024-07-05 09:37 UTC by VladimirBeria

2024-07-05 13:21 UTC, Lera24 commented on src/components/wt-tooltip/wt-tooltip.vue
> +  if (props.disabled) return;
Давай однією умовою запишемо цю і ту що нижче)

2024-07-09 08:28 UTC, dlohvinov requested changes

2024-07-09 08:28 UTC, dlohvinov commented on docs/pages/webitel-ui/components/wt-context-menu/wt-context-menu-docs.vue
> +      },
дока пишеться в мдшці

2024-07-09 11:39 UTC, Lera24 commented on docs/pages/webitel-ui/components/wt-tooltip/Readme.md
> +| triggers        | Array   | ['hover', 'focus', 'touch'] | `<wt-tooltip :triggers="['click']"></wt-tooltip>`        | see [Floating Vue](https://floating-vue.starpad.dev/api/#triggers) docs
івенти не дефолтні, а можливі значення

2024-07-09 14:04 UTC, Lera24 approved these changes

2024-07-09 14:07 UTC, dlohvinov approved these changes

2024-07-09 14:07 UTC, merged