Fear/implement wt tree table component
webitel/webitel-ui-sdk pull request #370
Opened 2024-11-26 10:16 UTC by stanislav-kozak

2024-12-04 11:53 UTC, Lera24 commented on src/assets/icons/sprite/index.js
> +import minus from './minus.svg';
ці вже є в іншому ПРі)
треба буде прибрати

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +<template>
і тут на гору)

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +    :style="[`--child-space:calc(var(--spacing-sm)*${nestedLevel})`, `--nested-level:${nestedLevel}`]"
це в стилі і дуже складно класи написані, треба спростити

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +        <div v-if="headerKey === 0" class="wt-tree-table__td__icon-wrapper">
!headerKey

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +          <wt-icon-btn v-for="n in lineCount" :key="n" icon="tree-line1" class="wt-tree-table-row__tree-icon"></wt-icon-btn>
що таке n?)

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +          <wt-icon-btn v-if="nestedLevel >= 1" icon="tree-cross1" class="wt-tree-table-row__tree-icon"></wt-icon-btn>
форматування)

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +          <wt-icon-btn v-if="!row[children]" class="wt-tree-table-row__show-button" :class="{'hidden': !row[children]}" :icon="collapsed ? 'plus' : 'minus'" @click="collapsed = !collapsed"></wt-icon-
тут точно всі класи потрібні?

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +  _selected: {
selected

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +        :_selected="_selected"
selected

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +    //display: flex;
?

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +    <table class="wt-tree-table__table">
може wt-tree-table__wrapper?

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +                class="wt-tree-table__th__sort-arrow wt-tree-table__th__sort-arrow--asc"
Мені не ок класи з asc, вони не розкривають суть

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +        :_selected="_selected"
і тут

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +          class="wt-tree-table__th__checkbox"
давай не checkbox

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +  function traverse(item) {
давай окремо винесемо

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +    if (item[props.children] && Array.isArray(item[props.children])) {
і ось ця стрічка просить також

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +// const columnsStyleHeader = computed(() => {
?

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +  let gridTemplateColumns = '';
стилями не можна вирішити?

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +  console.log('slots', slots);
?

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +const changeSelectItem = (item, selected) => {
3 однотипна функція в компоненті, не можна якось обєднати?

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +      changeSelectItem(props.data, false);
я б тернарником написала

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +    console.log('row', row);
поприбирай по коду всі консоль логи)

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +<style lang="scss">
один style не підходить?

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +//.wt-tree-table__tr__head {
і закоментований код також

2024-12-04 11:53 UTC, Lera24 commented on src/components/wt-expansion-panel/wt-expansion-panel.vue
> +      v-if="!hideTitle"
і тут

2024-12-06 12:50 UTC, stanislav-kozak commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +  _selected: {
Ні там треба саме _selected є ще окрема зміна selected ця логіка перенесена з звичайної таблиці wt-table

2024-12-06 12:50 UTC, stanislav-kozak commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +        :_selected="_selected"
Ні там треба саме _selected є ще окрема зміна selected ця логіка перенесена з звичайної таблиці wt-table

2024-12-06 12:52 UTC, stanislav-kozak commented on src/components/wt-tree-table/wt-tree-table.vue
> +                class="wt-tree-table__th__sort-arrow wt-tree-table__th__sort-arrow--asc"
Те ж саме що і више, за основу брався комопнент wt-table

2024-12-06 12:52 UTC, stanislav-kozak commented on src/components/wt-tree-table/wt-tree-table.vue
> +        :_selected="_selected"
Ні там треба саме _selected є ще окрема зміна selected ця логіка перенесена з звичайної таблиці wt-table

2024-12-06 12:52 UTC, stanislav-kozak commented on src/components/wt-tree-table/wt-tree-table.vue
> +          class="wt-tree-table__th__checkbox"
За основу брався комопнент wt-table

2024-12-06 12:54 UTC, stanislav-kozak commented on src/components/wt-tree-table/wt-tree-table.vue
> +  function traverse(item) {
Це одне ціле, в даному місці функція має певну логі для отбору необхідних елементів

2024-12-06 13:25 UTC, stanislav-kozak commented on src/components/wt-tree-table/wt-tree-table.vue
> +const changeSelectItem = (item, selected) => {
У всіх 3 функціяї різний функціонал traverse функції, яка проходиться по всіх елементах

2024-12-06 13:27 UTC, stanislav-kozak commented on src/components/wt-tree-table/wt-tree-table.vue
> +<style lang="scss">
Нажаль щоб імпортувати зміни потрібно без scoped робити імпорт,  а стилі які стосуються тільки таблиція я хочу тримати в scoped

2024-12-06 13:29 UTC, stanislav-kozak commented on src/assets/icons/sprite/index.js
> +import minus from './minus.svg';
Приберу як змержиться реквест з wt-tree

2024-12-10 10:53 UTC, Lera24 commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +.wt-tree-table-row--secondary {
щось тут не відповідність назви змінної і кольору(

2024-12-10 10:53 UTC, Lera24 commented on src/components/wt-tree-table/_internals/getSortOrder.js
> +const getNextSortOrder = (sort) => {
раз це використовується вже у більше ніж 1 компоненту, думаю треба винести на рівень вище з таблиці, а не дублювати

2024-12-10 10:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +            <div v-if="key === 0 && selectable">
!key && selectable не підійде?

2024-12-10 10:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +     * 'List of data, represented by table. '
якого формату може бути дата?

2024-12-10 10:53 UTC, Lera24 commented on src/components/wt-tree-table/wt-tree-table.vue
> +const dataHeaders = computed(() => {
а не було думки винести в композібл спільні з таблицею методи, компьютеди?

2024-12-10 10:53 UTC, Lera24 commented on src/components/wt-tree-table/_variables.scss
> +:root {
і варіабли також - вони просто дублюються
думаю і стилі також, треба б це якось винести

2024-12-10 10:53 UTC, Lera24 commented on src/playground.vue
>  <script setup>
прибери будь ласка)

2024-12-11 14:12 UTC, dlohvinov requested changes
хочеться закурити))

2024-12-11 14:12 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +        class="wt-tree-table__foot"
імхо то є блок
і чи точно воно тут треба? – функціонал морочний, суперечливий, і використовується тільки в 1му місці на всю систему. я би не тягнув його сюди, щоб не роздувати кодову багу

2024-12-11 14:12 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +        class="wt-tree-table__foot"
базу))

2024-12-11 14:12 UTC, dlohvinov commented on src/types/table/table-header.ts
> +export type TableHeader = {
тут всі пропси крім велью опціональні, якщо я не помиляюсь

2024-12-11 14:12 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +     * 'Accepts list of header objects. Draws text depending on "text" property, looks for data values through "value", "show" boolean controls visibility of a column (if undefined, all visible by de
а в доку хіба генерується тип даних, і інші коментарі основуючись на тайпскрипті, без jsdoc?
якщо ні, піддивись будь ласка в сусідніх компонентах (вт-баттон, наприклад), як описувати пропси, щоб колонки в доці гарно заповнювались

2024-12-11 14:12 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +     * 'List of data, represented by table. '
на `any` мені свариться транспайлер. боюсь, не збілдить її так
також, тут не ені
як мінімум, обжект мав би бути

2024-12-11 14:12 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +    sortable: boolean;
тре дефолт
і на інші пропси також

2024-12-11 14:12 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +  function traverse(item) {
тут негарно: функція не чиста, апдейтить якийсь верхній стейт.
думаю, Лера права: треба щоб траверс вертав цей селектед – і тоді можна буде його винести

2024-12-11 14:12 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +const getAllNestedElements = (item) => {
сейм до того шо вище

2024-12-11 14:12 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +const _selected = computed(() => {
було би класно зробити без _

2024-12-11 14:12 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +const dataHeaders = computed(() => {
плюсік, що пасувало би спільну логіку десь винести. не обовʼязково в компоузабл, але, реюзнути би за можливості

2024-12-11 14:12 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +const changeSelectItem = (item, selected) => {
чесно кажучи, я не дуже розумію, для чого виносити окремо метод траверс, щоб потім використати його у фор іч (замість мапа чи редʼюса)
ще й назва однакова – то теж плутає, як от Леру
і, з точки зору читання:
ти спершу дивишся на функцію якусь, потім дивишся внизу на використання, розумієш, нашо воно, і вертаєшся знову читати функцію. спершу вниз, потім вверх
якби це був код в середині проходу масива, то він би читався просто зверху вниз

2024-12-11 14:12 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +      changeSelectItem(props.data, false);
а я би ні :)
робимо висновок: вкусовщина, і, на ваш смак

2024-12-11 14:12 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +<style lang="scss">
Стас правий, не підходить(

2024-12-11 14:12 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +<style lang="scss" scoped>
оууу єєє!
знову стилі, однакові з табличкою)
треба винести, і реюзнути

от як мені згнати, чи треба в ці стилі вчитуватись, чи вони такі самі як і там?
чи там змінена 1-2 проперті зі 100?)

2024-12-12 11:33 UTC, stanislav-kozak commented on src/assets/icons/sprite/minus.svg
Відписав Жені, як отримаю відповідь або залишимо так або внесу зміни

2024-12-12 11:44 UTC, stanislav-kozak commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +          <wt-checkbox
Це не логіка чек боксу, чекбокс відповідає тільки за виділення елементу, від параметрів він може бути також скритий, та є окремо кнопка для розкриття дочірніх елементів, та вона також має свою умову для відображення, тому я би не хотів би це об'єднувати в одне

2024-12-12 12:00 UTC, stanislav-kozak commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +<style lang="scss" scoped>
Нажаль ні, все ж таки стилі в деревовидній таблиці відлічаються від тих що в звичайній, як мінімум тим що в звичайній все було завязано на display: grid, а в деревовидній таблиці на звичайному display table

2024-12-12 12:25 UTC, stanislav-kozak commented on src/types/table/table-data.ts
Цей тип видалив, бо нажаль той тип не описати, так як дата може бути будь якого типу :(

2024-12-12 12:35 UTC, stanislav-kozak commented on src/components/wt-tree-table/wt-tree-table.vue
> +<style lang="scss" scoped>
Нажаль там різні стилі, та є схожі, але вже више описував що стилі різні(

2024-12-12 16:21 UTC, stanislav-kozak commented on src/components/wt-tree-table/wt-tree-table.vue
> +     * 'Accepts list of header objects. Draws text depending on "text" property, looks for data values through "value", "show" boolean controls visibility of a column (if undefined, all visible by de
Ну в мене в доку підтягуються коментарі

2024-12-12 16:31 UTC, stanislav-kozak commented on src/components/wt-tree-table/wt-tree-table.vue
> +  function traverse(item) {
Повертати масив в функції traverse можливо але це костилі і буде дуже не охайно, перейменував функцію щоб було більш четабельно, та одну функцію переробив

2024-12-13 14:12 UTC, dlohvinov commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +               :key="treeLine" class="wt-tree-table-row__tree-icon"></div>
але ж це не іконка, а просто спесінг елемент?)

2024-12-13 14:12 UTC, dlohvinov commented on src/components/wt-tree-table-row/wt-tree-table-row.vue
> +      :nestingLevel="nestingLevel + 1"
спершу пропси, потім атрибути, потім івенти
і, пропси завжди кебаб кейсом

2024-12-13 14:12 UTC, dlohvinov commented on src/scripts/sortQueryAdapters.js
хорош!
мені теж це треба було десь, сварився шо немає в лібі)

2024-12-13 14:12 UTC, dlohvinov commented on src/composables/useTable/useTable.ts
а я шото пропустив, для чого, де юзається?

2024-12-13 14:12 UTC, dlohvinov commented on src/composables/useTable/useTable.ts
підозрюю що це шоби зашарити цей код між табличками. але ж в коді вт-тейбла немає використання цього скрипта?

2024-12-13 14:22 UTC, stanislav-kozak commented on src/composables/useTable/useTable.ts
Wt-table немає використання, можливо тому що цей файл є ts, та шоб використати його в table тебе скрипт переписати в вигляді компосішин апі з ts, та тоді він буде справно його бачити

2024-12-13 16:57 UTC, dlohvinov approved these changes

2024-12-13 16:57 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +     * 'Accepts list of header objects. Draws text depending on "text" property, looks for data values through "value", "show" boolean controls visibility of a column (if undefined, all visible by de
так мають не тільки коментарі підтягнутися, а і типи даних, і реквайрд, і дефолт
![image](https://github.com/user-attachments/assets/ef225341-5b3a-4af6-8dd0-9b10f388af66)
во, дивись. підозрюю, що у тебе тільки колонка велью і дескріпшен заповнюється – але хизи

2024-12-13 16:57 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +     * 'List of data, represented by table. '
я шото лайк над коментарем бачу, а зміни в коді не бачу – там і лишився ені(
і, відповідно, у інших використаннях дати також ені

2024-12-13 16:57 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +};
це не виходить переписати на пьюр фанкшени?

2024-12-13 16:57 UTC, dlohvinov commented on src/components/wt-tree-table/wt-tree-table.vue
> +const { dataHeaders } = useTable({
може `{ dataHeaders: headers }`?
і взагалі, імхо, неправильно вертати з компоузабла назву, яка тобі треба в компоненті – бо компоузабл про компонент не має знати
тобто, назва того шо вертається з компоузабла мала би бути `headers` – і вже тут її можна переписати за потреби
шариш, про що я?

2024-12-13 16:57 UTC, dlohvinov commented on src/composables/useTable/useTable.ts
> +export const useTable = ({ headers }) => {
я би пропонував назвати це `useWtTable`, тому що назва `useTableComponent` вже використоується в модулях – вона для компонента який містить в собі табличку, а не самої таблички

2024-12-30 10:50 UTC, merged